### ISSUE TITLE
[BUG] I've got this error today

### ISSUE THREAD

**Issue by jurgenjacobsen** [TimeForANinja/node-ytsr#105]
`
Error: type richShelfRenderer is not known
    at parseItem (C:\\node_modules\ytsr\lib\parseItem.js:69:13)
    at catchAndLogFunc (C:\\node_modules\ytsr\lib\parseItem.js:76:12)
    at module.exports (C:\\node_modules\ytsr\lib\parseItem.js:99:46)
    at C:\\node_modules\ytsr\lib\main.js:54:34
    at Array.map (<anonymous>)
    at module.exports (C:\\node_modules\ytsr\lib\main.js:54:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.exports.run (C:\\commands\play.js:14:32)
`

**Comment by brennanwilkes** [comment]
Also had this error. Posted a log dump to #106

**Comment by TimeForANinja** [comment]
fixed in https://github.com/TimeForANinja/node-ytsr/commit/8c5dc75e14a84d536fbd6d55855c6afec45e6dc4
available on git & npm as v3.3.0
