### ISSUE TITLE
Failed at func parseItem

### ISSUE THREAD

**Issue by Azarattum** [TimeForANinja/node-ytsr#113]
failed at func parseItem: Cannot read property 'simpleText' of undefined
```
TypeError: Cannot read property 'simpleText' of undefined
    at Object.exports.parseText (/home/amadeus/node_modules/ytsr/lib/utils.js:68:50)
    at parseShelf (/home/amadeus/node_modules/ytsr/lib/parseItem.js:371:17)
    at parseItem (/home/amadeus/node_modules/ytsr/lib/parseItem.js:30:14)
    at catchAndLogFunc (/home/amadeus/node_modules/ytsr/lib/parseItem.js:78:12)
    at module.exports (/home/amadeus/node_modules/ytsr/lib/parseItem.js:101:46)
    at /home/amadeus/node_modules/ytsr/lib/main.js:54:34
    at Array.map (<anonymous>)
    at module.exports (/home/amadeus/node_modules/ytsr/lib/main.js:54:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

This happened twice to me, not sure what the requests exactly were though. Here are the dumps:

[w5hemtkucw-1617032118584.txt](https://github.com/TimeForANinja/node-ytsr/files/6223085/w5hemtkucw-1617032118584.txt)
[6eykjfzci-1617033330855.txt](https://github.com/TimeForANinja/node-ytsr/files/6223084/6eykjfzci-1617033330855.txt)

```
os: linux-x64, node.js: v15.11.0, ytpl: 3.3.1
```

**Comment by TimeForANinja** [comment]
😉 thanks for the issue and providing the dumps
should be on npm in a sec
