### ISSUE TITLE
type includingResultsForRenderer is not known

### ISSUE THREAD

**Issue by cjh980402** [TimeForANinja/node-ytsr#132]
I get a err log of ytsr
```
(node:30245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: type includingResultsForRenderer is not known
    at parseItem (/home/ubuntu/bot/node_modules/ytsr/lib/parseItem.js:70:13)
    at catchAndLogFunc (/home/ubuntu/bot/node_modules/ytsr/lib/parseItem.js:77:12)
    at module.exports (/home/ubuntu/bot/node_modules/ytsr/lib/parseItem.js:100:46)
    at /home/ubuntu/bot/node_modules/ytsr/lib/main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (/home/ubuntu/bot/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.execute (/home/ubuntu/bot/commands/play.js:66:42)
    at async Client.<anonymous> (/home/ubuntu/bot/index.js:99:9)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type includingResultsForRenderer is not known
pls post the the files in /home/ubuntu/bot/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v14.16.1, ytpl: 3.5.0
********************************************************************************************************************************************************************************************************\
```

**Comment by TimeForANinja** [comment]
yep, ytsr catches and loggs those errors
most cases this means youtube changes sth about their replies
> pls post the the files in /home/ubuntu/bot/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues

can you provide this file?

**Comment by cjh980402** [comment]
```js
[
  {
    "includingResultsForRenderer": {
      "includingResultsFor": {
        "runs": [
          {
            "text": "Including results for:"
          }
        ]
      },
      "correctedQuery": {
        "runs": [
          {
            "text": "SherlockLives",
            "italics": true
          }
        ]
      },
      "correctedQueryEndpoint": {
        "clickTrackingParams": "CI4BEO8wGAAiEwjy5aamwb_xAhWHw0wCHWjaAW8=",
        "commandMetadata": {
          "webCommandMetadata": {
            "url": "/results?search_query=SherlockLives&sp=EgIQAQ%253D%253D",
            "webPageType": "WEB_PAGE_TYPE_SEARCH",
            "rootVe": 4724
          }
        },
        "searchEndpoint": {
          "query": "SherlockLives",
          "params": "EgIQAQ%3D%3D"
        }
      },
      "trackingParams": "CI4BEO8wGAAiEwjy5aamwb_xAhWHw0wCHWjaAW8="
    }
  },
  {
    "originalQuery": "#SherlockLives",
    "correctedQuery": "#SherlockLives",
    "results": 906893,
    "activeFilters": [],
    "refinements": [],
    "items": [],
    "continuation": null
  }
]
```
This is /home/ubuntu/bot/node_modules/ytsr/dumps/rik1edwg6b-1625061355396.txt

**Comment by TimeForANinja** [comment]
😉 will have a look

**Comment by TimeForANinja** [comment]
sorry that it took a bit
and thanks for being able to provide the file 😉
