### ISSUE TITLE
failed at func parseItem: type promotedSparklesWebRenderer is not known

### ISSUE THREAD

**Issue by MrDudis** [TimeForANinja/node-ytsr#149]
Hey, I am sometimes getting this error when searching for youtube videos.

```
Error: type promotedSparklesWebRenderer is not known
at parseItem (/application/node_modules/ytsr/lib/parseItem.js:74:13)
at catchAndLogFunc (/application/node_modules/ytsr/lib/parseItem.js:81:12)
at module.exports (/application/node_modules/ytsr/lib/parseItem.js:104:46)
at /application/node_modules/ytsr/lib/main.js:53:34
at Array.map (<anonymous>)
at module.exports (/application/node_modules/ytsr/lib/main.js:53:25)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

failed at func parseItem: type promotedSparklesWebRenderer is not known
pls post the the files in /application/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.13.1, ytsr: 3.5.3
```

Here is the file requested for debugging:
[8qoq0imkzt-1640908773365.txt](https://github.com/TimeForANinja/node-ytsr/files/7803949/8qoq0imkzt-1640908773365.txt)

Thanks ;)

**Comment by syj67507** [comment]
Seeing this as well, but it seems like the search still returns successfully for me. Just adding my files for debugging to add on to this.

[msi7p99kxl-1641759589696.txt](https://github.com/TimeForANinja/node-ytsr/files/7835858/msi7p99kxl-1641759589696.txt)
[pyq7drrc5o-1641759671335.txt](https://github.com/TimeForANinja/node-ytsr/files/7835859/pyq7drrc5o-1641759671335.txt)
[sgji08mxm8-1641759621360.txt](https://github.com/TimeForANinja/node-ytsr/files/7835860/sgji08mxm8-1641759621360.txt)
[5huvf2cabi-1641759671113.txt](https://github.com/TimeForANinja/node-ytsr/files/7835861/5huvf2cabi-1641759671113.txt)
[74qgxget7v-1641759621402.txt](https://github.com/TimeForANinja/node-ytsr/files/7835862/74qgxget7v-1641759621402.txt)
[h2xeakzuj9-1641759671370.txt](https://github.com/TimeForANinja/node-ytsr/files/7835863/h2xeakzuj9-1641759671370.txt)
.

**Comment by FadelesSpade** [comment]
I'm also seeing this issue.
The search result is still successful. 
It is also not a video specific issue, as after receiving this error I immediately re-queued the same song and the issue didn't arise.

[05zfoxjak-1641800578247.txt](https://github.com/TimeForANinja/node-ytsr/files/7837394/05zfoxjak-1641800578247.txt)
