### ISSUE TITLE
Error: type promotedSparklesWebRenderer is not known

### ISSUE THREAD

**Issue by cainotis** [TimeForANinja/node-ytsr#152]
I received this error

```bash
Error: type promotedSparklesWebRenderer is not known
    at parseItem (/mnt/e/Projetos/Bots/Milho/node_modules/ytsr/lib/parseItem.js:74:13)
    at catchAndLogFunc (/mnt/e/Projetos/Bots/Milho/node_modules/ytsr/lib/parseItem.js:81:12)
    at module.exports (/mnt/e/Projetos/Bots/Milho/node_modules/ytsr/lib/parseItem.js:104:46)
    at /mnt/e/Projetos/Bots/Milho/node_modules/ytsr/lib/main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (/mnt/e/Projetos/Bots/Milho/node_modules/ytsr/lib/main.js:53:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Client.<anonymous> (/mnt/e/Projetos/Bots/Milho/src/index.ts:139:26)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type promotedSparklesWebRenderer is not known
pls post the the files in /mnt/e/Projetos/Bots/Milho/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.13.2, ytsr: 3.5.3
********************************************************************************************************************************************************************************************************
```

[biwmpyz5zc-1643730455439.txt](https://github.com/TimeForANinja/node-ytsr/files/7979790/biwmpyz5zc-1643730455439.txt)

**Comment by AKASGaming** [comment]
can vouch, started getting this error too

**Comment by TimeForANinja** [comment]
closed with https://github.com/TimeForANinja/node-ytsr/commit/e3de97c0ea0cfa6c67c71fc937f1ecef419db07f
