### ISSUE TITLE
Error: type reelShelfRenderer is not known

### ISSUE THREAD

**Issue by Rainymy** [TimeForANinja/node-ytsr#154]
Hello, has any of you got this error yet? I get this error kinda randomly. Does anyone have any ideas? This error doesn't do anything except print this error on my terminal. 

```
Error: type reelShelfRenderer is not known
    at parseItem (C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\lib\parseItem.js:74:13)
    at catchAndLogFunc (C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\lib\parseItem.js:81:12)
    at module.exports (C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\lib\parseItem.js:104:46)
    at C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async YouTube.searchVideos (C:\Users\Qubiet\Desktop\Node.js\Kimchord\server\API\youtube.js:104:27)
    at async YouTube.getYoutubeData (C:\Users\Qubiet\Desktop\Node.js\Kimchord\server\API\youtube.js:78:22)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type reelShelfRenderer is not known
pls post the the files in C:\Users\Qubiet\Desktop\Node.js\Kimchord\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.13.2, ytsr: 3.6.0
********************************************************************************************************************************************************************************************************\
```

**Comment by mafineeek** [comment]
Its bug while lib reads Youtube Shorts videos.

**Comment by R2D2VaderBeef** [comment]
Hi, I've just encountered the same error. However, I haven't actually experienced any issues due to it. Here is, as requested by the error message, my most recent dump and system information.
`os: win32-x64, node.js: v16.8.0, ytsr: 3.5.3`
[Uploading sv1yhfaf38-1648056299480.txt…]()

**Comment by mafineeek** [comment]
Try to keep search queries as detailed as you can, and limit results from it to avoid getting yt shorts.

**Comment by Rainymy** [comment]
I take this as solved, should I close?
