### ISSUE TITLE
adSlotRenderer is not known

### ISSUE THREAD

**Issue by InfinityJxck** [TimeForANinja/node-ytsr#171]
Evening! I'm using npm package `discord-music-player` and I get the following issue **only when loading a playlist into the system**.

```
Error: type adSlotRenderer is not known
    at parseItem (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:81:13)
    at catchAndLogFunc (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:88:12)
    at module.exports (A:\GitHub\Framework-v14\node_modules\ytsr\lib\parseItem.js:111:46)
    at A:\GitHub\Framework-v14\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (A:\GitHub\Framework-v14\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.search (A:\GitHub\Framework-v14\node_modules\discord-music-player\dist\utils\Utils.js:82:26)
    at async A:\GitHub\Framework-v14\node_modules\discord-music-player\dist\utils\Utils.js:242:32

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type adSlotRenderer is not known
pls post the the files in A:\GitHub\Framework-v14\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.17.0, ytsr: 3.8.0
********************************************************************************************************************************************************************************************************\
```

Paste available at: https://paste.jx.wtf/iroqarivin.md

Files: https://paste.jx.wtf/wopugejodo.json // https://paste.jx.wtf/rekenozeya.json
(There's more but they're virtually the same)

Any help is appreciated, cheers folks!

**Comment by Reply2Zain** [comment]
I also have been getting the same error. 'adSlotRenderer' is a new field that isn't accounted for. To fix this I added an additional case where the ads are 'parsed'. In  your project, go to `node_module/ytsr/lib/parseItem.js` 

Add this on line `59` of `lib/parseItem.js`.
```
case 'adSlotRenderer':
```

It should look like this
```js
switch (type) {
    // other code... 

    // Skip Adds for now
    case 'adSlotRenderer': // this is the fix
    case 'carouselAdRenderer':
}
```

Re-run your project and the issue should be resolved. 

PS: This should be done after you install your packages. Any "npm install" might overwrite these changes.

**Comment by mtripg6666tdr** [comment]
having same error :)

**Comment by mtripg6666tdr** [comment]
this is still present
