### ISSUE TITLE
TypeError: filterWrapper is not iterable

### ISSUE THREAD

**Issue by abaza738** [TimeForANinja/node-ytsr#180]
## Error
```
/<project_dir>/node_modules/ytsr/lib/utils.js:23
  for (const filterGroup of filterWrapper) {
                            ^

TypeError: filterWrapper is not iterable
    at Object.exports.parseFilters (/<project_dir>/node_modules/ytsr/lib/utils.js:23:29)
    at module.exports (/<project_dir>/node_modules/ytsr/lib/main.js:60:24)
    at runMicrotasks (<anonymous>)
    ...
```

## Details
For some reason, the value of [`searchSubMenuRenderer`](https://github.com/TimeForANinja/node-ytsr/blob/d5580d6829b96da443f8a98363b28446c7575213/lib/utils.js#L21) is sometimes returned as this:
```json
{
  "trackingParams": "CDIQkXUiEwjSt4yGr4T9AhU2O_EFHQmlCT8="
}
```
Hence `filterWrapper` is undefined.

**Comment by eugabrielsilva** [comment]
Same error! Waiting for a fix, since this lib is the main tool used in my application... @TimeForANinja

**Comment by ArmyaAli** [comment]
I'm having this issue as well. This occurs so randomly as well

**Comment by TimeForANinja** [comment]
can you try changing [`filterWrapper`](https://github.com/TimeForANinja/node-ytsr/blob/master/lib/utils.js#L21) to sth like
```
- const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;
+ const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups || [];
```
can't recreate the error myself...

**Comment by abaza738** [comment]
I guess I can submit a PR with that change, but I don't have any knowledge of what the code does in there.

**Comment by dev-syn** [comment]
I also have this issue now and then it just randomly occurs like when I try searching for various songs some fail and then when I try again it works I can't reproduce it every time

**Comment by AaronMeyers** [comment]
i’m also having this issue

**Comment by dafatov** [comment]
Created a PR related to this defect. See plz. @TimeForANinja 
https://github.com/TimeForANinja/node-ytsr/pull/203

**Comment by BrijeshNenwani** [comment]
Earlier, It was failing 4 out of 5 times, and now it doesn't fail at all, thank you for this 👉https://github.com/TimeForANinja/node-ytsr/issues/180#issuecomment-1507709961 
BTW, your library serves one of the major feature in my application, and its awesome.

**Comment by NotYuzuru** [comment]
> can you try changing [`filterWrapper`](https://github.com/TimeForANinja/node-ytsr/blob/master/lib/utils.js#L21) to sth like
> 
> ```
> - const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;
> + const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups || [];
> ```
> 
> can't recreate the error myself...

this worked indeed, thanks!
