### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'browseEndpoint')

### ISSUE THREAD

**Issue by s3849606** [TimeForANinja/node-ytsr#198]
Full error message:

```
TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:431:45)
    at parseMovie (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:346:12)
    at parseItem (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:26:14)
    at catchAndLogFunc (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:90:12)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:113:46)
    at C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:71:30
    at async Promise.all (index 40)
    at async Object.execute (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:69:27)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.16.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\
TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:431:45)
    at parseMovie (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:346:12)
    at parseItem (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:26:14)
    at catchAndLogFunc (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:90:12)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:113:46)
    at C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:71:30
    at async Promise.all (index 74)
    at async Object.execute (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:69:27)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.16.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\
TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:431:45)
    at parseMovie (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:346:12)
    at parseItem (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:26:14)
    at catchAndLogFunc (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:90:12)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\parseItem.js:113:46)
    at C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:71:30
    at async Promise.all (index 48)
    at async Object.execute (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:69:27)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.16.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\
TypeError: Cannot read properties of undefined (reading 'title')
    at C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:85:74
    at Array.filter (<anonymous>)
    at Object.execute (C:\Users\james\OneDrive\Documents\Discord Bot\RythmRaymond-Test\commands\playlist.js:85:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
[p5tkht2mcm-1682838132848.txt](https://github.com/TimeForANinja/node-ytsr/files/11360761/p5tkht2mcm-1682838132848.txt)

**Comment by athammer** [comment]
same issue as https://github.com/TimeForANinja/node-ytsr/issues/195
