### ISSUE TITLE
It doesn't result now

### ISSUE THREAD

**Issue by KENLIEPLAYSPH** [TimeForANinja/node-ytsr#208]
It doesn't give response now

**Comment by YuriVivaldi** [comment]
Same here

the `getFilters` function gives back an empty map, with a simple call like:
```
getFilters(query, {}).then((first_fils: any) => {
   console.log("FILTERS", first_fils);
}
```

outputs:

```
Aug 02 17:19:31 P80S node[691]: FILTERS Map(0) {}

```

**Comment by Michal-Szczepaniak** [comment]
I am getting 
```
TypeError: filterWrapper is not iterable
    at Object.exports.parseFilters (/home/foidbgen/Programs/sfosworkspace/microtube/js/node_modules/ytsr/lib/utils.js:23:29)
    at module.exports (/home/foidbgen/Programs/sfosworkspace/microtube/js/node_modules/ytsr/lib/main.js:60:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
