### ISSUE TITLE
"pls post the the files in [...]\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues"

### ISSUE THREAD

**Issue by BugBatts** [TimeForANinja/node-ytsr#211]
Note: all instances of [...] are the same path to my Discord.js bot that I have obfuscated for privacy

I randomly checked my bot's console as I usually do, and I found the following error message:

TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner ([...]\node_modules\ytsr\lib\parseItem.js:431:45)
    at parseMovie ([...]\node_modules\ytsr\lib\parseItem.js:346:12)
    at parseItem ([...]\node_modules\ytsr\lib\parseItem.js:26:14)
    at catchAndLogFunc ([...]\node_modules\ytsr\lib\parseItem.js:90:12)
    at module.exports ([...]\node_modules\ytsr\lib\parseItem.js:113:46)
    at [...]\node_modules\ytsr\lib\main.js:53:34
    at Array.map (\<anonymous\>)
    at module.exports ([...]\node_modules\ytsr\lib\main.js:53:25)
    at runMicrotasks (\<anonymous\>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in [...]\node_modules\ytsr\dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: win32-x64, node.js: v16.20.0, ytsr: 3.8.2
********************************************************************************************************************************************************************************************************\

I am following the instructions stated directly above in making this issue. The file is dated August 14th, 2023 at 3:54PM EST (roughly 30 minutes before this issue is posted) if that matters.

[6l5j7kirw-1692042853859.txt](https://github.com/TimeForANinja/node-ytsr/files/12339315/6l5j7kirw-1692042853859.txt)

**Comment by MrManiacc** [comment]
Bumping this. Same error for me. Using version 3.8.4

**Comment by continentaldivide** [comment]
Same error for me last night, same stack trace except the second line was invoking `parsePlaylist` instead of `parseMovie`.

os: linux-x64, node.js: v18.15.0, ytsr: 3.8.4

[30e04m94p-1699319597445.txt](https://github.com/TimeForANinja/node-ytsr/files/13291477/30e04m94p-1699319597445.txt)
