### ISSUE TITLE
error

### ISSUE THREAD

**Issue by isaacgamemati** [TimeForANinja/node-ytsr#215]
/home/container/node_modules/ytsr/lib/parseItem.js:437
  const ownerUrl = owner.navigationEndpoint.browseEndpoint.canonicalBaseUrl ||
                                            ^

TypeError: Cannot read properties of undefined (reading 'browseEndpoint')
    at _parseOwner (/home/container/node_modules/ytsr/lib/parseItem.js:437:45)
    at parsePlaylist (/home/container/node_modules/ytsr/lib/parseItem.js:210:50)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:18:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\

**Comment by isaacgamemati** [comment]
![image](https://github.com/TimeForANinja/node-ytsr/assets/64173239/f835abe0-1a78-45bd-bc6b-f62d2f91fa66)
