### ISSUE TITLE
I can't search for videos!

### ISSUE THREAD

**Issue by Peppy8651** [TimeForANinja/node-ytsr#90]
I have issues with two examples: the wip version of ytsr on npm, and the current wip version on Github.

NPM wip version:
-

When I search for videos on the npm version of ytsr, it just doesn't finish searching. It starts searching for videos but it doesn't finish. I tried to console log my results directly below the lines that search for the results, but it doesn't even get to the console log line. It just sits there and does nothing or at least that's what I think. It doesn't go on with the code either it just keeps awaiting on ytsr to search.

Github wip version:
-
When using the Github wip version that I just downloaded today, it makes my .catch() go off. If I remove .catch(), it throws this error:
```
Unhandled promise rejection: MinigetError: Status code: 400
    at ClientRequest.<anonymous> (C:\Users\Owner\Documents\BirdyBirdy\node_modules\miniget\dist\index.js:197:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10) {
  statusCode: 400
}
```

Neither work and I have no idea what to do at all to fix it.

**Comment by Noctisq** [comment]
I have the same problem with the NPM wip version, it doesn't search anything and i doesn't throw any error.

**Comment by Peppy8651** [comment]
It was fixed. You can use the git version or your can use npm install ytsr@wip again. There was a version just released that fixes this all. Thanks to TimeForANinja for fixing this and helping me on the Discord server.
