### ISSUE TITLE
Cannot read property 'simpleText' of undefined

### ISSUE THREAD

**Issue by Alexandre94H** [TimeForANinja/node-ytsr#93]
```shell
TypeError: Cannot read property 'simpleText' of undefined
    at Object.exports.parseText (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/utils.js:67:50)
    at parseShowingResultsFor (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/parseItem.js:227:40)
    at parseItem (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/parseItem.js:37:14)
    at catchAndLogFunc (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/parseItem.js:68:12)
    at module.exports (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/parseItem.js:88:46)
    at /home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/main.js:57:34
    at Array.map (<anonymous>)
    at module.exports (/home/alexandre/Projects/Sempiternel/node_modules/ytsr/lib/main.js:57:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read property 'simpleText' of undefined
pls post the the files in /home/alexandre/Projects/Sempiternel/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
********************************************************************************************************************************************************************************************************\
```

**Comment by UsingPython** [comment]
I had the same issue once. I tried another search query and the error doesn't appear again, so i can't reproduce it atm.

**Comment by TimeForANinja** [comment]
can you provide the file asked for?

**Comment by CatsMiaow** [comment]
Three errors occur.

`os: linux-x64, node.js: v12.19.0, ytpl: 2.0.2`

```sh
TypeError: Cannot read property 'simpleText' of undefined
     at Object.exports.parseText (/home/bot/node_modules/ytsr/lib/utils.js:67:50)
     at parseShowingResultsFor (/home/bot/node_modules/ytsr/lib/parseItem.js:230:40)
     at parseItem (/home/bot/node_modules/ytsr/lib/parseItem.js:37:14)
     at catchAndLogFunc (/home/bot/node_modules/ytsr/lib/parseItem.js:68:12)
     at module.exports (/home/bot/node_modules/ytsr/lib/parseItem.js:91:46)
     at /home/bot/node_modules/ytsr/lib/main.js:57:34
     at Array.map (<anonymous>)
     at module.exports (/home/bot/node_modules/ytsr/lib/main.js:57:25)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
```sh
TypeError: Cannot read property 'searchEndpoint' of undefined
     at /home/bot/node_modules/ytsr/lib/parseItem.js:238:56
     at Array.map (<anonymous>)
     at parseHorizontalCardListRenderer (/home/bot/node_modules/ytsr/lib/parseItem.js:237:40)
     at parseItem (/home/bot/node_modules/ytsr/lib/parseItem.js:39:14)
     at catchAndLogFunc (/home/bot/node_modules/ytsr/lib/parseItem.js:68:12)
     at module.exports (/home/bot/node_modules/ytsr/lib/parseItem.js:91:46)
     at /home/bot/node_modules/ytsr/lib/main.js:57:34
     at Array.map (<anonymous>)
     at module.exports (/home/bot/node_modules/ytsr/lib/main.js:57:25)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
```sh
Error: type clarificationRenderer is not known
     at parseItem (/home/bot/node_modules/ytsr/lib/parseItem.js:61:13)
     at catchAndLogFunc (/home/bot/node_modules/ytsr/lib/parseItem.js:68:12)
     at module.exports (/home/bot/node_modules/ytsr/lib/parseItem.js:91:46)
     at /home/bot/node_modules/ytsr/lib/main.js:57:34
     at Array.map (<anonymous>)
     at module.exports (/home/bot/node_modules/ytsr/lib/main.js:57:25)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by CatsMiaow** [comment]
```ts
await ytsr('la campanela', { limit: 10 });
```
@TimeForANinja I am getting a `simpleText` error in the code above.

**Comment by TimeForANinja** [comment]
👍🏿 was working on these issues for the last 3+ hours
fix should come shortly

**Comment by TimeForANinja** [comment]
closed with https://github.com/TimeForANinja/node-ytsr/releases/tag/3.0.0
